import { createApiThunk } from '../apiThunk'

export const fetchAllCollegeList = createApiThunk('college/fetchAllCollegeList')

export const fetchAgentCollegeList = createApiThunk('college/fetchAgentCollegeList')
export const fetchStateList = createApiThunk('college/fetchStateList')
export const fetchCityList = createApiThunk('college/fetchCityList')
export const fetchCourseList = createApiThunk('college/fetchCourseListList')
export const addCollegeBasicDetails = createApiThunk('college/addCollegeBasicDetails')
export const fileUploadlogo = createApiThunk('college/fileUploadlogo')
export const fileUploadThumbnail = createApiThunk('college/fileUploadThumbnail')
export const fileUploadBrochure = createApiThunk('college/fileUploadBrochure')
export const fileUploadGallary = createApiThunk('college/fileUploadGallary')
export const deleteCollegeBasicDetails = createApiThunk('college/deleteCollegeBasicDetails')
export const deleteCollegeCourseOffered = createApiThunk('college/deleteCollegeCourseOffered')
export const deleteCollegeHighlight = createApiThunk('college/deleteCollegeHighlight')
export const addCollegeDescription = createApiThunk('college/addCollegeDescription')
export const addCollegeHighlight = createApiThunk('college/addCollegeHighlight')
export const addCollegeFacilities = createApiThunk('college/addCollegeFacilities')
export const addCollegeCourseOffered = createApiThunk('college/addCollegeCourseOffered')
export const addCollegeGallary = createApiThunk('college/addCollegeGallary')
export const fetchCollegeById = createApiThunk('college/fetchCollegeById')
export const fetchCourseOfferedById = createApiThunk('college/fetchCourseOfferedById')
export const fetchCollegeDiscriptionById = createApiThunk('college/fetchCollegeDiscriptionById')
export const fetchCollegeHighlightsById = createApiThunk('college/fetchCollegeHighlightsById')
export const fetchCollegeCommonById = createApiThunk('college/fetchCollegeCommonById')
export const fetchCollegeGallaryById = createApiThunk('college/fetchCollegeGallaryById')
export const createNewCollege = createApiThunk('newCollege/AddNewCollege')
export const updateCollegeById = createApiThunk('newCollege/updateCollegeById')
export const fetchNewCollegeById = createApiThunk('newCollege/fetchNewCollegeById')
export const deleteNewCollegeById = createApiThunk('newCollege/deleteNewCollegeById')
